import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Annouce from "@/components/annoucement";
import Header from "@/components/Header";
import FooterB from "@/components/FooterB";
import { CartProvider } from "@/context/CartContext";
import {ClerkProvider} from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <CartProvider>
    <html lang="en">
      <body className={inter.className}>
        <Annouce/>
        <Header/>
        {children}
        <FooterB/>
        </body>
    </html>
    </CartProvider>
    </ClerkProvider>
  );
}
